[Breq 1210][Breq 1358] voithos docs changes
breqwatr/voithos pull request #100
Opened 2021-03-17 17:00 UTC by waqasnazir03

This PR addresses #1210 and #1358.

2021-03-17 20:34 UTC, kylep requested changes

2021-03-17 20:34 UTC, kylep commented on docs/openstack-ceph.md
> +./config/cinder/cinder.conf
This didn't actually work. We needed to make cinder-volume.conf, cinder-api.conf, and cinder-scheduler.conf each. I don't get why, though.

2021-03-19 16:21 UTC, waqasnazir03 commented on docs/openstack-ceph.md
> +./config/cinder/cinder.conf
@kylep I have addressed your comment in my latest commit. Instead of putting `cinder.conf` under `config/cinder/`, we need to put it under `config/`. 
https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/cinder/tasks/config.yml#L82

2021-03-19 16:22 UTC, waqasnazir03 commented
@kylep I have addressed your comment. Please have another look when you get a chance.

2021-04-05 14:35 UTC, kylep approved these changes

2021-04-05 14:35 UTC, merged