[Breq 1736] VMs cpu utilization script
breqwatr/voithos pull request #129
Opened 2021-11-29 15:06 UTC by waqasnazir03

This PR addresses #1736.

2021-11-29 15:12 UTC, kylep requested changes

2021-11-29 15:12 UTC, kylep commented on voithos/lib/util/util.py
> +import datetime
This is confusing, why are you importing datetime and also date from datetime below it?

2021-11-29 15:12 UTC, kylep commented on voithos/lib/util/util.py
> +           uuid = ([e for e in cmd_info if "uuid=" in e])
Why the brackets?

2021-11-29 15:12 UTC, kylep commented on voithos/lib/util/util.py
> +        if proc.name() == 'qemu-system-x86_64':
When the whole loop needs to go inside an if check like this, consider writing it as:
```
for proc in psutil.process_iter():
    if proc.name() != 'qemu-system-x86_64':
        continue  #  Skip this process, we only want qemu-system VMs
    ....
```

2021-11-29 16:24 UTC, waqasnazir03 commented
@kylep 
I have addressed your comments. Please have another look when you get a chance.

2021-11-30 15:55 UTC, kylep approved these changes

2021-12-01 18:44 UTC, merged