BREQ-1285-VoithosPreventOverwritingGPOBackups
breqwatr/voithos pull request #92
Opened 2021-02-17 20:38 UTC by ruthrosals

Prevent to create backups if there is an existing backup.

2021-02-18 14:50 UTC, kylep requested changes

2021-02-18 14:50 UTC, kylep commented on powershell/voithos.psm1
> +}
Wrapping a whole function in an if block only to have an else that does nothing and print an error is a pattern that over time causes the code to get indented really far to the right, and hard to follow.

Instead of
```
function x {
  if thing {
     ...
     ...
     ...
   } else {
     write-warning 'cant do the thing'
     # function returns now
   }
}
```

Try

```
function x {
  if ! thing {
    write-warning 'cant do the thing'
    return
  }
  ...
  ...
  ...
}
```

2021-02-19 00:54 UTC, ruthrosals reviewed
I made some changes can you please verify it? Thanks

2021-02-22 18:49 UTC, kylep approved these changes

2021-02-22 18:56 UTC, evan-narayan approved these changes

2021-02-24 15:53 UTC, merged