BREQ1316_UpdateRegistryHiveFunctions
breqwatr/voithos pull request #94
Opened 2021-02-25 15:05 UTC by ruthrosals

1. Updated the following functions: 

- Add-HklmRegistryHive 
- Remove-HklmRegistryHive

2. Created Test-HklmRegistryHive Function 
3. Updated the following functions to use the RegistryHive functions:  

- Remove-VMWareTools
- Backup-MountedGPOSettings
- Set-MountedGpoStartupScript  

4. Tested all versions of OS: Windows 2012, 2012R2, 2016, 2019, 10. 
5.  Removed Set-RunOnceScript and Get-RunOnceScript as they were replaced by Set-MountedGPOStartScript.

2021-02-25 16:17 UTC, evan-narayan approved these changes

2021-02-25 21:22 UTC, kylep commented on powershell/voithos.psm1
> +    [Parameter(Mandatory=$True)] [ValidateSet("SOFTWARE","SYSTEM","SECURITY")] [ValidatePattern('^[A-Z]',Options='None')] [string] $Hive
ValidateSet is cool, didnt know about it

2021-02-25 21:26 UTC, kylep requested changes

2021-02-25 21:26 UTC, kylep commented on powershell/voithos.psm1
> +  Write-Host REG LOAD "HKLM\TEMP$Hive" $hklmPath
There's a trailing space at the end of this. They don't really hurt anything but if you can get your IDE to highlight them, its cleaner to not have trailing spaces.

2021-02-25 21:26 UTC, kylep commented on powershell/voithos.psm1
> +}
trailing space again, they're all over. Again, you dont need to fix this ones, just suggesting your configure your IDE to see them.

2021-02-25 21:26 UTC, kylep commented on powershell/voithos.psm1
> +   ### Return the value of a given registry key in the HKLM/$Hive hive ###
indentation of this comment is too far right, should line up with the next line

2021-02-25 21:26 UTC, kylep commented on powershell/voithos.psm1
> +   ### Return the value of a given registry key in the HKLM/$Hive hive ###
Also is this comment even correct? It looks like this is testing if a hive is mounted

2021-02-25 21:26 UTC, kylep commented on powershell/voithos.psm1
> +  Test-HklmRegistryHive -Hive SOFTWARE
I think this just writes if the hive is loaded or not, right? Should we error out if it's not loaded?

2021-02-26 19:07 UTC, ruthrosals reviewed
Kyle, whenever you have a moment, can you please review the changes? Thanks,

2021-02-26 19:07 UTC, ruthrosals commented on powershell/voithos.psm1
> +    [Parameter(Mandatory=$True)] [ValidateSet("SOFTWARE","SYSTEM","SECURITY")] [ValidatePattern('^[A-Z]',Options='None')] [string] $Hive
Yes, it is pretty good ValidateSet parameter.   Made the following changes:                                                                    
     1.  Removed the trailing spaces.                                                                                                                                       
     2. Modified the comment in the  Test-HklmRegistryHive function.   
 Yes, you are right Test-HklmRegistryHive function tests if the hive is loaded or unloaded. I tried to use the try-catch only to verify it that can be used as an option, but it does not work for REG LOAD command. The REG LOAD /UNLOAD commands automatically throws the errors if the hive doesn't load or unload correctly. I tested some options to cause an error and I was getting the errors.

2021-03-03 15:38 UTC, kylep approved these changes

2021-03-03 15:38 UTC, merged